### ISSUE TITLE
Better users management

### ISSUE THREAD

**Issue by jonatan1609** [thewh1teagle/NmapDetectorDashboard#1]
Why don't you use [flask-login](https://flask-login.readthedocs.io/en/latest/) instead of handling the session by yourself? The code could be much shorter and easier to understand.

**Comment by thewh1teagle** [comment]
@jonatan1609 
I tried first with flask-login but it felt that it will be more complicated so I left it.

**Comment by jonatan1609** [comment]
> I tried first with flask-login but it felt that it will be more complicated so I left it.
Well, not really. Let me know if you want me to mention you in a small project I made to see a minimal example with this and pony.orm.

**Comment by thewh1teagle** [comment]
Sounds good
I would love to thank you

**Comment by jonatan1609** [comment]
> Sounds good
> I would love to, thank you

https://github.com/jonatan1609/FlaskLogin-HelloWorld
